Repository mensatt/frontend, pull requests merged in 2022-10, with the labels that each got.

#141 Style popup thing
  src/styles/popups.scss
Labels: enhancement

#154 feat: Rename the german translation for having no nickname
  public/locales/de/common.json
  public/locales/en/common.json
Labels: enhancement, low priority

#163 feat: Make logo in footer clickable
  src/components/footer/Footer.module.scss
  src/components/footer/Footer.tsx
Labels: enhancement, low priority

#167 fix: Disable show more tags button
  src/components/occurrence/tags/OccurrenceTags.module.scss
Labels: low priority

#164 feat: Improve review modal
  src/components/occurrence/review-modal/form/Form.module.scss
  src/components/occurrence/review-modal/form/Form.tsx
Labels: enhancement, help wanted, low priority
